CAPE_SIGNATURES = {
    'accesses_mailslot': "",
    'accesses_netlogon_regkey': "",
    'accesses_primary_patition': "",
    'accesses_recyclebin': "",
    'accesses_sysvol': "",
    'adds_admin_user': "",
    'adds_user': "",
    'allaple_mutexes': "",
    'alphacrypt_behavior': "",
    'alters_windows_utility': "",
    'andromeda_behavior': "",
    'andromut_mutexes': "",
    'angler_js': "",
    'anomalous_deletefile': "",
    'antianalysis_detectfile': "",
    'antianalysis_detectreg': "",
    'antiav_360_libs': 'Anti-antivirus',
    'antiav_ahnlab_libs': 'Anti-antivirus',
    'antiav_apioverride_libs': 'Anti-antivirus',
    'antiav_avast_libs': 'Anti-antivirus',
    'antiav_bitdefender_libs': 'Anti-antivirus',
    'antiav_bullgaurd_libs': 'Anti-antivirus',
    'antiav_detectfile': 'Anti-antivirus',
    'antiav_detectreg': 'Anti-antivirus',
    'antiav_emsisoft_libs': 'Anti-antivirus',
    'antiav_nthookengine_libs': 'Anti-antivirus',
    'antiav_qurb_libs': 'Anti-antivirus',
    'antiav_servicestop': 'Anti-antivirus',
    'antiav_srp': 'Anti-antivirus',
    'antidebug_devices': "",
    'antidebug_windows': "",
    'antidebug_addvectoredexceptionhandler': "",
    'antidebug_checkremotedebuggerpresent': "",
    'antidebug_debugactiveprocess': "",
    'antidebug_gettickcount': "",
    'antidebug_guardpages': "",
    'antidebug_ntcreatethreadex': "",
    'antidebug_ntsetinformationthread': "",
    'antidebug_outputdebugstring': "",
    'antidebug_setunhandledexceptionfilter': "",
    'antiemu_windefend': 'Anti-emulation',
    'antiemu_wine_func': 'Anti-emulation',
    'antiemu_wine_reg': 'Anti-emulation',
    'antisandbox_check_userdomain': 'Anti-sandbox',
    'antisandbox_cuckoo': 'Anti-sandbox',
    'antisandbox_cuckoo_files': 'Anti-sandbox',
    'antisandbox_cuckoocrash': 'Anti-sandbox',
    'antisandbox_fortinet_files': 'Anti-sandbox',
    'antisandbox_joe_anubis_files': 'Anti-sandbox',
    'antisandbox_mouse_hook': 'Anti-sandbox',
    'antisandbox_restart': 'Anti-sandbox',
    'antisandbox_sboxie_libs': 'Anti-sandbox',
    'antisandbox_sboxie_mutex': 'Anti-sandbox',
    'antisandbox_sboxie_objects': 'Anti-sandbox',
    'antisandbox_script_timer': 'Anti-sandbox',
    'antisandbox_sleep': 'Anti-sandbox',
    'antisandbox_sunbelt_files': 'Anti-sandbox',
    'antisandbox_sunbelt_libs': 'Anti-sandbox',
    'antisandbox_suspend': 'Anti-sandbox',
    'antisandbox_threattrack_files': 'Anti-sandbox',
    'antisandbox_unhook': 'Anti-sandbox',
    'antivirus_virustotal': "",
    'antivm_directory_objects': 'Anti-vm',
    'antivm_generic_bios': 'Anti-vm',
    'antivm_generic_cpu': 'Anti-vm',
    'antivm_generic_disk': 'Anti-vm',
    'antivm_generic_disk_setupapi': 'Anti-vm',
    'antivm_generic_diskreg': 'Anti-vm',
    'antivm_generic_scsi': 'Anti-vm',
    'antivm_generic_services': 'Anti-vm',
    'antivm_generic_system': 'Anti-vm',
    'antivm_hyperv_keys': 'Anti-vm',
    'antivm_parallels_keys': 'Anti-vm',
    'antivm_vbox_devices': 'Anti-vm',
    'antivm_vbox_files': 'Anti-vm',
    'antivm_vbox_keys': 'Anti-vm',
    'antivm_vbox_libs': 'Anti-vm',
    'antivm_vbox_provname': 'Anti-vm',
    'antivm_vbox_window': 'Anti-vm',
    'antivm_vmware_devices': 'Anti-vm',
    'antivm_vmware_events': 'Anti-vm',
    'antivm_vmware_files': 'Anti-vm',
    'antivm_vmware_keys': 'Anti-vm',
    'antivm_vmware_libs': 'Anti-vm',
    'antivm_vmware_mutexes': 'Anti-vm',
    'antivm_vpc_files': 'Anti-vm',
    'antivm_vpc_keys': 'Anti-vm',
    'antivm_vpc_mutex': 'Anti-vm',
    'antivm_xen_keys': 'Anti-vm',
    'api_spamming': "",
    'apocalypse_stealer_file_behavior': "",
    'arkei_files': "",
    'azorult_mutexes': "",
    'bad_certs': "",
    'bad_ssl_certs': "",
    'banker_cridex': "",
    'banker_prinimalka': "",
    'banker_spyeye_mutexes': "",
    'banker_zeus_mutex': "",
    'banker_zeus_p2p': "",
    'banker_zeus_url': "",
    'bcdedit_command': "",
    'betabot_behavior': "",
    'bitcoin_opencl': "",
    'blacknet_mutexes': "",
    'blackrat_apis': "",
    'blackrat_mutexes': "",
    'blackrat_network_activity': "",
    'blackrat_registry_keys': "",
    'bootkit': "",
    'bot_athenahttp': "",
    'bot_dirtjumper': "",
    'bot_drive': "",
    'bot_drive2': "",
    'bot_kraken_mutexes': "",
    'bot_madness': "",
    'bot_russkill': "",
    'browser_addon': "",
    'browser_helper_object': "",
    'browser_needed': "",
    'browser_scanbox': "",
    'browser_security': "",
    'browser_startpage': "",
    'bypass_firewall': "",
    'cape_detected_threat': "",
    'cape_extracted_config': "",
    'cape_extracted_content': "",
    'captures_screenshot': "",
    'carberp_mutex': "",
    'cerber_behavior': "",
    'changes_trust_center_settings': "",
    'chimera_behavior': "",
    'clamav': "",
    'clears_logs': "",
    'clickfraud_cookies': "",
    'clickfraud_volume': "",
    'cmdline_http_link': "",
    'cmdline_obfuscation': "",
    'cmdline_process_discovery': "",
    'cmdline_reversed_http_link': "",
    'cmdline_switches': "",
    'cmdline_terminate': "",
    'codelux_behavior': "",
    'commandline_forfiles_wildcard': "",
    'commandline_long_string': "",
    'compression': "",
    'copies_self': "",
    'crat_mutexes': "",
    'creates_exe': "",
    'creates_largekey': "",
    'creates_nullvalue': "",
    'createtoolhelp32snapshot_module_enumeration': "",
    'critical_process': "",
    'cryptbot_files': "",
    'cryptbot_network': "",
    'cryptomix_mutexes': "",
    'cryptopool_domains': "",
    'cryptowall_behavior': "",
    'cve_2014_6332': "",
    'cve_2015_2419_js': "",
    'cve_2016-0189': "",
    'cve_2016_7200': "",
    'cypherit_mutexes': "",
    'cyrptomining_stratum_command': "",
    'darkcomet_regkeys': "",
    'datop_loader': "",
    'dcrat_behavior': "",
    'dcrat_files': "",
    'dcrat_mutexes': "",
    'dead_connect': "",
    'dead_link': "",
    'debugs_self': "",
    'decoy_document': "",
    'decoy_image': "",
    'decryption': "",
    'deepfreeze_mutex': "",
    'deletes_self': "",
    'deletes_shadow_copies': "",
    'deletes_system_state_backup': "",
    'dep_bypass': "",
    'dep_disable': "",
    'dharma_mutexes': "",
    'direct_hdd_access': "",
    'disable_folder_options': "",
    'disable_run_command': "",
    'disables_app_launch': "",
    'disables_appv_virtualization': "",
    'disables_auto_app_termination': "",
    'disables_backups': "",
    'disables_browser_warn': "",
    'disables_context_menus': "",
    'disables_cpl_disable': "",
    'disables_event_logging': "",
    'disables_mappeddrives_autodisconnect': "",
    'disables_notificationcenter': "",
    'disables_power_options': "",
    'disables_restore_default_state': "",
    'disables_smartscreen': "",
    'disables_spdy': "",
    'disables_startmenu_search': "",
    'disables_system_restore': "",
    'disables_uac': "",
    'disables_vba_trust_access': "",
    'disables_wer': "",
    'disables_wfp': "",
    'disables_windows_defender': "",
    'disables_windows_defender_logging': "",
    'disables_windows_file_protection': "",
    'disables_windowsupdate': "",
    'disables_winfirewall': "",
    'document_script_exe_drop': "",
    'doppelganging': "",
    'dotnet_clr_usagelog_regkeys': "",
    'dotnet_code_compile': "",
    'dotnet_csc_build': "",
    'downloader_cabby': "",
    'downloads_from_filehosting': "",
    'dridex_behavior': "",
    'driver_filtermanager': "",
    'driver_load': "",
    'dropper': "",
    'dynamic_function_loading': "",
    'dyre_behavior': "",
    'echelon_files': "",
    'enables_wdigest': "",
    'encrypt_data_agenttesla_http': "",
    'encrypt_data_agentteslat2_http': "",
    'encrypt_data_nanocore': "",
    'encrypted_ioc': "",
    'encrypts_pcinfo': "",
    'enumerates_running_processes': "",
    'evilgrab': "",
    'excel4_macro_urls': "",
    'exe_dropper_js': "",
    'exec_crash': "",
    'exploit_getbasekerneladdress': "",
    'exploit_gethaldispatchtable': "",
    'exploit_heapspray': "",
    'explorer_http': "",
    'family_proxyback': "",
    'file_credential_store_access': "",
    'file_credential_store_write': "",
    'firefox_disables_process_tab': "",
    'fleercivet_mutex': "",
    'fonix_mutexes': "",
    'gandcrab_mutexes': "",
    'generic_metrics': "",
    'generic_phish': "",
    'geodo_banking_trojan': "",
    'germanwiper_mutexes': "",
    'get_clipboard_data': "",
    'gondad_js': "",
    'gootkit_behavior': "",
    'guloader_apis': "",
    'gulpix_behavior': "",
    'h1n1_behavior': "",
    'hancitor_behavior': "",
    'hawkeye_behavior': "",
    'heapspray_js': "",
    'hides_recycle_bin_icon': "",
    'http_request': "",
    'https_urls': "",
    'ie_disables_process_tab': "",
    'ie_martian_children': "",
    'infostealer_bitcoin': "",
    'infostealer_browser': "",
    'infostealer_browser_password': "",
    'infostealer_cookies': "",
    'infostealer_ftp': "",
    'infostealer_im': "",
    'infostealer_keylog': "",
    'infostealer_mail': "",
    'injection_create_remote_thread': "",
    'injection_createremotethread': "",
    'injection_explorer': "",
    'injection_inter_process': "",
    'injection_needextension': "",
    'injection_network_traffic': "",
    'injection_process_hollowing': "",
    'injection_runpe': "",
    'injection_rwx': "",
    'injection_set_window_long': "",
    'injection_themeinitapihook': "",
    'internet_dropper': "",
    'invalid_authenticode_signature': "",
    'ipc_namedpipe': "",
    'java_js': "",
    'js_phish': "",
    'js_suspicious_redirect': "",
    'karagany_files': "",
    'karagany_system_event_objects': "",
    'kazybot_behavior': "",
    'kelihos_behavior': "",
    'ketrican_regkeys': "",
    'kibex_behavior': "",
    'koadic_apis': "",
    'koadic_network_activity': "",
    'kovter_behavior': "",
    'limerat_mutexes': "",
    'limerat_regkeys': "",
    'locker_regedit': "",
    'locker_taskmgr': "",
    'locky_behavior': "",
    'lodarat_file_behavior': "",
    'log4shell': "",
    'lokibot_mutexes': "",
    'long_commandline': "",
    'lsa_tampering': "",
    'lsass_credential_dumping': "",
    'malicious_dynamic_function_loading': "",
    'mapped_drives_uac': "",
    'masquerade_process_name': "",
    'mass_data_encryption': "",
    'masslogger_artifacts': "",
    'masslogger_files': "",
    'masslogger_version': "",
    'medusalocker_mutexes': "",
    'medusalocker_regkeys': "",
    'mimics_agent': "",
    'mimics_extension': "",
    'mimics_filetime': "",
    'mimics_icon': "",
    'mimikatz_modules': "",
    'modifies_attachment_manager': "",
    'modifies_certs': "",
    'modifies_desktop_wallpaper': "",
    'modifies_hostfile': "",
    'modifies_oem_information': "",
    'modify_proxy': "",
    'modify_security_center_warnings': "",
    'modify_uac_prompt': "",
    'modirat_behavior': "",
    'move_file_on_reboot': "",
    'multiple_explorer_instances': "",
    'multiple_useragents': "",
    'nemty_mutexes': "",
    'nemty_network_activity': "",
    'nemty_note': "",
    'nemty_regkeys': "",
    'neshta_files': "",
    'neshta_mutexes': "",
    'neshta_regkeys': "",
    'netwire_behavior': "",
    'network_anomaly': "",
    'network_bind': "",
    'network_cnc_http': "",
    'network_cnc_https_archive': "",
    'network_cnc_https_free_webshoting': "",
    'network_cnc_https_generic': "",
    'network_cnc_https_pastesite': "",
    'network_cnc_https_payload': "",
    'network_cnc_https_socialmedia': "",
    'network_cnc_https_telegram': "",
    'network_cnc_https_temp_urldns': "",
    'network_cnc_https_tempstorage': "",
    'network_cnc_https_urlshortener': "",
    'network_cnc_https_useragent': "",
    'network_cnc_smtps_exfil': "",
    'network_cnc_smtps_generic': "",
    'network_country_distribution': "",
    'network_dga': "",
    'network_dga_fraunhofer': "",
    'network_dns_blockchain': "",
    'network_dns_doh_tls': "",
    'network_dns_idn': "",
    'network_dns_opennic': "",
    'network_dns_paste_site': "",
    'network_dns_reverse_proxy': "",
    'network_dns_suspicious_querytype': "",
    'network_dns_temp_file_storage': "",
    'network_dns_temp_urldns': "",
    'network_dns_tunneling_request': "",
    'network_dns_url_shortener': "",
    'network_document_http': "",
    'network_excessive_udp': "",
    'network_fake_useragent': "",
    'network_http': "",
    'network_icmp': "",
    'network_irc': "",
    'network_multiple_direct_ip_connections': "",
    'network_open_proxy': "",
    'network_questionable_host': "",
    'network_questionable_http_path': "",
    'network_questionable_https_path': "",
    'network_smtp': "",
    'network_tor': "",
    'network_tor_service': "",
    'network_torgateway': "",
    'neutrino_js': "",
    'njrat_regkeys': "",
    'nuclear_js': "",
    'nymaim_behavior': "",
    'obliquerat_files': "",
    'obliquerat_mutexes': "",
    'obliquerat_network_activity': "",
    'odbcconf_bypass': "",
    'office_addinloading': "",
    'office_anomalous_feature': "",
    'office_code_page': "",
    'office_com_load': "",
    'office_cve2017_11882': "",
    'office_cve2017_11882_network': "",
    'office_cve_2021_40444': "",
    'office_cve_2021_40444_m2': "",
    'office_dde_command': "",
    'office_dotnet_load': "",
    'office_flash_load': "",
    'office_macro': "",
    'office_macro_autoexecution': "",
    'office_macro_ioc': "",
    'office_macro_malicious_prediction': "",
    'office_macro_suspicious': "",
    'office_martian_children': "",
    'office_mshtml_load': "",
    'office_perfkey': "",
    'office_postscript': "",
    'office_security': "",
    'office_suspicious_processes': "",
    'office_vb_load': "",
    'office_wmi_load': "",
    'office_write_exe': "",
    'okrum_mutexes': "",
    'orcusrat_behavior': "",
    'origin_langid': "",
    'origin_resource_langid': "",
    'overwites_admin_password': "",
    'overwrites_accessibility_utility': "",
    'owa_web_shell_files': "",
    'packer_armadillo_mutex': "",
    'packer_armadillo_regkey': "",
    'packer_aspack': "",
    'packer_aspirecrypt': "",
    'packer_bedsprotector': "",
    'packer_confuser': "",
    'packer_enigma': "",
    'packer_entropy': "",
    'packer_mpress': "",
    'packer_nate': "",
    'packer_nspack': "",
    'packer_smartassembly': "",
    'packer_spices': "",
    'packer_themida': "",
    'packer_titan': "",
    'packer_unknown_pe_section_name': "",
    'packer_upx': "",
    'packer_vmprotect': "",
    'packer_yoda': "",
    'parallax_mutexes': "",
    'pdf_annot_urls': "",
    'pe_compile_timestomping': "",
    'persistence_ads': "",
    'persistence_autorun': "",
    'persistence_autorun_tasks': "",
    'persistence_bootexecute': "",
    'persistence_ifeo': "",
    'persistence_rdp_registry': "",
    'persistence_rdp_shadowing': "",
    'persistence_registry_script': "",
    'persistence_safeboot': "",
    'persistence_service': "",
    'persistence_shim_database': "",
    'persistence_slient_process_exit': "",
    'persists_dev_util': "",
    'phorpiex_mutexes': "",
    'physical_drive_access': "",
    'plugx': "",
    'polymorphic': "",
    'pony_behavior': "",
    'potential_overwrite_mbr': "",
    'poullight_files': "",
    'powerpool_mutexes': "",
    'powershell_command_suspicious': "",
    'powershell_network_connection': "",
    'powershell_renamed': "",
    'powershell_renamed_commandline': "",
    'powershell_reversed': "",
    'powershell_scriptblock_logging': "",
    'powershell_variable_obfuscation': "",
    'prevents_safeboot': "",
    'process_creation_suspicious_location': "",
    'process_interest': "",
    'process_needed': "",
    'procmem_yara': "",
    'protonbot_mutexes': "",
    'punch_plus_plus_pcres': "",
    'purplewave_mutexes': "",
    'purplewave_network_activity': "",
    'pysa_mutexes': "",
    'quilclipper_behavior': "",
    'quilclipper_mutexes': "",
    'qulab_files': "",
    'qulab_mutexes': "",
    'raccoon_behavior': "",
    'ransomware_dmalocker': "",
    'ransomware_extensions': "",
    'ransomware_file_modifications': "",
    'ransomware_files': "",
    'ransomware_message': "",
    'ransomware_radamant': "",
    'ransomware_recyclebin': "",
    'ransomware_revil_regkey': "",
    'rat_beebus_mutexes': "",
    'rat_fynloski_mutexes': "",
    'rat_luminosity': "",
    'rat_nanocore': "",
    'rat_pcclient': "",
    'rat_plugx_mutexes': "",
    'rat_poisonivy_mutexes': "",
    'rat_quasar_mutexes': "",
    'rat_spynet': "",
    'rat_xtreme_mutexes': "",
    'ratsnif_mutexes': "",
    'rdptcp_key': "",
    'reads_self': "",
    'recon_beacon': "",
    'recon_checkip': "",
    'recon_fingerprint': "",
    'recon_programs': "",
    'recon_systeminfo': "",
    'reg_binary': "",
    'registry_credential_dumping': "",
    'registry_credential_store_access': "",
    'registry_lsa_secrets_access': "",
    'regsvr32_squiblydoo_dll_load': "",
    'remcos_files': "",
    'remcos_mutexes': "",
    'remcos_regkeys': "",
    'removes_networking_icon': "",
    'removes_pinned_programs': "",
    'removes_security_maintenance_icon': "",
    'removes_startmenu_defaults': "",
    'removes_username_startmenu': "",
    'removes_windows_defender_contextmenu': "",
    'removes_zoneid_ads': "",
    'renamer_mutexes': "",
    'revil_mutexes': "",
    'rig_js': "",
    'rtf_anomaly_characterset': "",
    'rtf_anomaly_version': "",
    'rtf_aslr_bypass': "",
    'rtf_embedded_content': "",
    'rtf_embedded_office_file': "",
    'rtf_exploit_static': "",
    'satan_mutexes': "",
    'scrcons_wmi_script_consumer': "",
    'script_created_process': "",
    'script_network_activity': "",
    'script_tool_executed': "",
    'secure_login_phishing': "",
    'securityxploded_modules': "",
    'set_clipboard_data': "",
    'sets_autoconfig_url': "",
    'shifu_behavior': "",
    'silverlight_js': "",
    'snake_ransom_mutexes': "",
    'sniffer_winpcap': "",
    'sodinokibi_behavior': "",
    'spawns_dev_util': "",
    'spicyhotpot_behavior': "",
    'spoofs_procname': "",
    'spooler_access': "",
    'spooler_svc_start': "",
    'spreading_autoruninf': "",
    'squiblydoo_bypass': "",
    'squiblytwo_bypass': "",
    'stack_pivot': "",
    'stack_pivot_file_created': "",
    'stack_pivot_process_create': "",
    'static_authenticode': "",
    'static_dotnet_anomaly': "",
    'static_java': "",
    'static_pdf': "",
    'static_pe_anomaly': "",
    'static_pe_pdbpath': "",
    'static_rat_config': "",
    'static_versioninfo_anomaly': "",
    'stealth_childproc': "",
    'stealth_file': "",
    'stealth_hidden_extension': "",
    'stealth_hiddenreg': "",
    'stealth_hide_notifications': "",
    'stealth_network': "",
    'stealth_timeout': "",
    'stealth_webhistory': "",
    'stealth_window': "",
    'stop_ransom_mutexes': "",
    'stop_ransomware_cmd': "",
    'stop_ransomware_registry': "",
    'sundown_js': "",
    'suricata_alert': "",
    'suspicious_certutil_use': "",
    'suspicious_command_tools': "",
    'suspicious_ioctl_scsipassthough': "",
    'suspicious_js_script': "",
    'suspicious_mpcmdrun_use': "",
    'suspicious_ping_use': "",
    'sysinternals_psexec': "",
    'sysinternals_tools': "",
    'system_account_disovery_cmd': "",
    'system_info_disovery_cmd': "",
    'system_info_disovery_pwsh': "",
    'system_network_discovery_cmd': "",
    'system_network_discovery_pwsh': "",
    'system_user_disovery_cmd': "",
    'tampers_etw': "",
    'tampers_powershell_logging': "",
    'targeted_flame': "",
    'territorial_disputes_sigs': "",
    'tinba_behavior': "",
    'transacted_hollowing': "",
    'trickbot_mutex': "",
    'trickbot_task_delete': "",
    'trochilusrat_apis': "",
    'troldesh_behavior': "",
    'uac_bypass_cmstp': "",
    'uac_bypass_cmstpcom': "",
    'uac_bypass_delegateexecute_sdclt': "",
    'uac_bypass_eventvwr': "",
    'uac_bypass_fodhelper': "",
    'unpacker': "",
    'upatre_behavior': "",
    'ursnif_behavior': "",
    'user_enum': "",
    'uses_adfind': "",
    'uses_powershell_copyitem': "",
    'uses_rdp_clip': "",
    'uses_remote_desktop_session': "",
    'uses_windows_utilities': "",
    'uses_windows_utilities_appcmd': "",
    'uses_windows_utilities_cipher': "",
    'uses_windows_utilities_clickonce': "",
    'uses_windows_utilities_csvde_ldifde': "",
    'uses_windows_utilities_dsquery': "",
    'uses_windows_utilities_esentutl': "",
    'uses_windows_utilities_finger': "",
    'uses_windows_utilities_mode': "",
    'uses_windows_utilities_nltest': "",
    'uses_windows_utilities_ntdsutil': "",
    'uses_windows_utilities_to_create_scheduled_task': "",
    'uses_windows_utilities_xcopy': "",
    'vawtrak_behavior': "",
    'venomrat_mutexes': "",
    'vidar_behavior': "",
    'virtualcheck_js': "",
    'virus': "",
    'volatility_devicetree_1': "",
    'volatility_handles_1': "",
    'volatility_ldrmodules_1': "",
    'volatility_ldrmodules_2': "",
    'volatility_malfind_1': "",
    'volatility_malfind_2': "",
    'volatility_modscan_1': "",
    'volatility_svcscan_1': "",
    'volatility_svcscan_2': "",
    'volatility_svcscan_3': "",
    'warzonerat_files': "",
    'warzonerat_regkeys': "",
    'web_shell_files': "",
    'web_shell_processes': "",
    'webmail_phish': "",
    'whois_create': "",
    'windows_defender_powershell': "",
    'wiper_zeroedbytes': "",
    'wmi_create_process': "",
    'wmi_script_process': "",
    'wmic_command_suspicious': "",
    'writes_sysvol': "",
    'xpertrat_files': "",
    'xpertrat_mutexes': ""
}

# TODO: Add these signatures to the CAPEv2 community from the Cuckoo community
# CUCKOO_SIGNATURES = {
#     'TAPI_DP_mutex': 'Fraud',
#     'UFR_Stealer': 'RAT',
#     'adds_user_admin': 'Persistence',
#     'alina_pos_file': 'Point-of-sale',
#     'alina_pos_url': 'Point-of-sale',
#     'allocates_execute_remote_process': 'Injection',
#     'allocates_rwx': 'Injection',
#     'amsi_bypass': 'Bypass',
#     'android_antivirus_virustotal': 'AntiVirus Hit',
#     'android_dangerous_permissions': 'Suspicious Android API',
#     'android_dynamic_code': 'Suspicious Android API',
#     'android_embedded_apk': 'Suspicious Android API',
#     'android_google_play_diff': 'Suspicious Android API',
#     'android_native_code': 'Suspicious Android API',
#     'android_reflection_code': 'Suspicious Android API',
#     'andromeda': 'RAT',
#     'antiav_whitespace': 'Anti-antivirus',
#     'antiemu_wine': 'Anti-emulation',
#     'antisandbox_clipboard': 'Anti-sandbox',
#     'antisandbox_file': 'Anti-sandbox',
#     'antisandbox_foregroundwindows': 'Anti-sandbox',
#     'antisandbox_idletime': 'Anti-sandbox',
#     'antisandbox_sunbelt': 'Anti-sandbox',
#     'antivirus_irma': 'Anti-antivirus',
#     'antivm_disk_size': 'Anti-vm',
#     'antivm_firmware': 'Anti-vm',
#     'antivm_generic_ide': 'Anti-vm',
#     'antivm_network_adapters': 'Anti-vm',
#     'antivm_parallels_window': 'Anti-vm',
#     'antivm_queries_computername': 'Anti-vm',
#     'antivm_sandboxie': 'Anti-vm',
#     'antivm_shared_device': 'Anti-vm',
#     'antivm_vbox_acpi': 'Anti-vm',
#     'antivm_virtualpc': 'Anti-vm',
#     'antivm_virtualpc_illegal_instruction': 'Anti-vm',
#     'antivm_virtualpc_window': 'Anti-vm',
#     'antivm_vmware_in_instruction': 'Anti-vm',
#     'antivm_vmware_window': 'Anti-vm',
#     'application_aborted_broadcast_receiver': 'Suspicious Android API',
#     'application_deleted_app': 'Suspicious Android API',
#     'application_executed_shell_command': 'Suspicious Android API',
#     'application_installed_app': 'Suspicious Android API',
#     'application_queried_account_info': 'Suspicious Android API',
#     'application_queried_installed_apps': 'Suspicious Android API',
#     'application_queried_phone_number': 'Suspicious Android API',
#     'application_queried_private_information': 'Suspicious Android API',
#     'application_recording_audio': 'Suspicious Android API',
#     'application_registered_receiver_runtime': 'Suspicious Android API',
#     'application_sent_sms_messages': 'Suspicious Android API',
#     'application_stopped_processes': 'Suspicious Android API',
#     'application_uses_location': 'Suspicious Android API',
#     'application_using_the_camera': 'Suspicious Android API',
#     'applocker_bypass': 'Bypass',
#     'ardamax_mutexes': 'Infostealer',
#     'athena_url': 'Trojan',
#     'av_detect_china_key': 'Anti-antivirus',
#     'bad_certificate': 'Stealth',
#     'bagle': 'Worm',
#     'bandook': 'RAT',
#     'banker_bancos': 'Banker',
#     'banker_spyeye_url': 'Banker',
#     'banker_tinba_mutexes': 'RAT',
#     'banking_mutexes': 'Banker',
#     'banload': 'Trojan',
#     'begseabugtd_mutexes': 'Trojan',
#     'betabot_url': 'BOT',
#     'blackenergy_mutexes': 'Rootkit',
#     'blackpos_url': 'Point-of-sale',
#     'bladabindi_mutexes': 'RAT',
#     'bot_kelihos': 'BOT',
#     'bot_kovter': 'BOT',
#     'bot_vnloader_url': 'BOT',
#     'bozok_key': 'RAT',
#     'btc': 'RAT',
#     'c24_url': 'BOT',
#     'chanitor_mutexes': 'Ransomware',
#     'checks_debugger': 'Anti-Debug',
#     'checks_kernel_debugger': 'Anti-Debug',
#     'clear_permission_event_logs': 'Stealth',
#     'clears_event_logs': 'Stealth',
#     'cloud_dropbox': 'Cloud',
#     'cloud_google': 'Cloud',
#     'cloud_mediafire': 'Cloud',
#     'cloud_mega': 'Cloud',
#     'cloud_rapidshare': 'Cloud',
#     'cloud_wetransfer': 'Cloud',
#     'coinminer_mutexes': 'Trojan',
#     'console_output': 'Infostealer',
#     'creates_doc': 'Suspicious Office',
#     'creates_hidden_file': 'Stealth',
#     'creates_null_reg_entry': 'Stealth',
#     'creates_service': 'Persistence',
#     'creates_shortcut': 'Persistence',
#     'creates_user_folder_exe': 'Downloader',
#     'credential_dumping_lsass': 'Persistence',
#     'credential_dumping_lsass_access': 'Persistence',
#     'cryptlocker': 'Ransomware',
#     'cryptomining_stratum_command': 'Cryptocurrency',
#     'cybergate': 'RAT',
#     'darkcloud': 'RAT',
#     'darwin_code_injection': 'Injection',
#     'ddos556': 'RAT',
#     'ddos_blackrev_mutexes': 'BOT',
#     'ddos_darkddos_mutexes': 'BOT',
#     'ddos_eclipse_mutexes': 'BOT',
#     'ddos_ipkiller_mutexes': 'BOT',
#     'dead_host': 'C2',
#     'decay': 'RAT',
#     'decebal_mutexes': 'Point-of-sale',
#     'deletes_executed_files': 'Persistence',
#     'dep_heap_bypass': 'Exploit',
#     'dep_stack_bypass': 'Exploit',
#     'dexter': 'Point-of-sale',
#     'disables_ie_http2': 'Infostealer',
#     'disables_proxy': 'Infostealer',
#     'disables_security': 'Anti-antivirus',
#     'disables_spdy_chrome': 'Infostealer',
#     'disables_spdy_firefox': 'Infostealer',
#     'disables_spdy_ie': 'Infostealer',
#     'dll_load_uncommon_file_types': 'Suspicious DLL',
#     'dns_freehosting_domain': 'C2',
#     'dnsserver_dynamic': 'DynDNS',
#     'document_close': 'Suspicious Office',
#     'document_open': 'Suspicious Office',
#     'dofoil': 'Virus',
#     'dumped_buffer': 'Injection',
#     'dumped_buffer2': 'Injection',
#     'dyreza': 'Banker',
#     'emotet_behavior': 'Infostealer',
#     'evilbot': 'RAT',
#     'excel_datalink': 'Downloader',
#     'exe_appdata': 'Persistence',
#     'exec_bits_admin': 'Suspicious Execution Chain',
#     'exec_waitfor': 'Bypass',
#     'expiro': 'RAT',
#     'exploit_blackhole_url': 'Exploit',
#     'exploitkit_mutexes': 'Exploit',
#     'fakeav_mutexes': 'RAT',
#     'farfli': 'RAT',
#     'fesber_mutexes': 'Worm',
#     'fraudtool_fakerean': 'Fraud',
#     'gaelicum': 'Worm',
#     'generates_crypto_key': 'Stealth',
#     'ghostbot': 'RAT',
#     'has_authenticode': 'Stealth',
#     'has_office_eps': 'Suspicious Office',
#     'has_wmi': 'WMI',
#     'hesperbot': 'RAT',
#     'html_flash': 'Exploit',
#     'icepoint': 'RAT',
#     'im_btb': 'IM',
#     'im_qq': 'IM',
#     'infinity': 'RAT',
#     'infostealer_clipboard': 'Infostealer',
#     'infostealer_derusbi_files': 'Infostealer',
#     'infostealer_keylogger': 'Infostealer',
#     'injection_modifies_memory': 'Injection',
#     'injection_network_trafic': 'Injection',
#     'injection_ntsetcontextthread': 'Injection',
#     'injection_process_search': 'Injection',
#     'injection_queueapcthread': 'Injection',
#     'injection_resumethread': 'Injection',
#     'injection_write_memory': 'Injection',
#     'injection_write_memory_exe': 'Injection',
#     'installs_appinit': 'Persistence',
#     'installs_bho': 'Adware',
#     'ircbrute': 'RAT',
#     'isrstealer_url': 'Infostealer',
#     'istealer_url': 'Infostealer',
#     'jackpos_file': 'Point-of-sale',
#     'jackpos_url': 'Point-of-sale',
#     'javascript_commandline': 'Persistence',
#     'jeefo_mutexes': 'Virus',
#     'jintor_mutexes': 'Infostealer',
#     'js_anti_analysis': 'Anti-analysis',
#     'js_eval': 'Exploit',
#     'js_iframe': 'Anti-analysis',
#     'js_suspicious': 'Exploit',
#     'karagany': 'RAT',
#     'karakum': 'RAT',
#     'katusha': 'RAT',
#     'killdisk': 'Trojan',
#     'koobface': 'RAT',
#     'krepper_mutexes': 'Worm',
#     'kuluoz_mutexes': 'RAT',
#     'locates_sniffer': 'Anti-analysis',
#     'locker_cmd': 'Locker',
#     'luder': 'RAT',
#     'magania_mutexes': 'RAT',
#     'malicious_document_urls': 'Downloader',
#     'martian_command_process': 'Suspicious Execution Chain',
#     'memdump_ip_urls': 'C2',
#     'memdump_tor_urls': 'C2',
#     'memdump_urls': 'Injection',
#     'memdump_yara': 'Injection',
#     'metasploit_shellcode': 'Hacking tool',
#     'minerbot': 'RAT',
#     'miningpool': 'Cryptocurrency',
#     'modifies_boot_config': 'Persistence',
#     'modifies_firefox_configuration': 'Infostealer',
#     'modifies_proxy_autoconfig': 'Infostealer',
#     'modifies_proxy_override': 'Infostealer',
#     'modifies_security_center_warnings': 'Stealth',
#     'modifies_zoneid': 'Stealth',
#     'moves_self': 'Stealth',
#     'nakbot': 'RAT',
#     'netshadow': 'RAT',
#     'netwire': 'RAT',
#     'network_dns_txt_lookup': 'DynDNS',
#     'network_document_file': 'Downloader',
#     'network_downloader_exe': 'Downloader',
#     'network_http_post': 'C2',
#     'network_ip_exe': 'Downloader',
#     'network_wscript_downloader': 'Downloader',
#     'networkdyndns_checkip': 'DynDNS',
#     'nitol': 'RAT',
#     'njrat': 'RAT',
#     'nolookup_communication': 'C2',
#     'obfus_mutexes': 'Trojan',
#     'office_appinfo_version': 'Suspicious Office',
#     'office_check_doc_name': 'Suspicious Office',
#     'office_check_project_name': 'Suspicious Office',
#     'office_check_window': 'Suspicious Office',
#     'office_count_dirs': 'Suspicious Office',
#     'office_create_object': 'Suspicious Office',
#     'office_dde': 'Dropper',
#     'office_eps_strings': 'Suspicious Office',
#     'office_http_request': 'Suspicious Office',
#     'office_indirect_call': 'Suspicious Office',
#     'office_packager': 'Suspicious Office',
#     'office_platform_detect': 'Suspicious Office',
#     'office_recent_files': 'Suspicious Office',
#     'office_uses_wmi': 'WMI',
#     'office_vuln_guid': 'Suspicious Office',
#     'office_vuln_modules': 'Suspicious Office',
#     'oldrea': 'RAT',
#     'p2p_cnc': 'C2',
#     'packer_polymorphic': 'Packer',
#     'pdf_attachments': 'Suspicious PDF API',
#     'pdf_javascript': 'Suspicious PDF API',
#     'pdf_openaction': 'Suspicious PDF API',
#     'pdf_openaction_js': 'Suspicious PDF API',
#     'pe_features': 'Packer',
#     'pe_unknown_resource_name': 'Packer',
#     'peid_packer': 'Packer',
#     'perflogger': 'Infostealer',
#     'persistence_registry_exe': 'Persistence',
#     'persistence_registry_javascript': 'Persistence',
#     'persistence_registry_powershell': 'Persistence',
#     'pidief': 'Trojan',
#     'poebot': 'RAT',
#     'poisonivy': 'RAT',
#     'ponfoy': 'RAT',
#     'ponybot_url': 'BOT',
#     'pos_poscardstealer_url': 'Point-of-sale',
#     'powerfun': 'Injection',
#     'powershell_bitstransfer': 'PowerShell',
#     'powershell_c2dns': 'PowerShell',
#     'powershell_ddi_rc4': 'PowerShell',
#     'powershell_dfsp': 'PowerShell',
#     'powershell_di': 'PowerShell',
#     'powershell_download': 'PowerShell',
#     'powershell_empire': 'Hacking tool',
#     'powershell_meterpreter': 'Hacking tool',
#     'powershell_reg_add': 'PowerShell',
#     'powershell_request': 'PowerShell',
#     'powershell_unicorn': 'PowerShell',
#     'powerworm': 'PowerShell',
#     'privilege_luid_check': 'Persistence',
#     'process_martian': 'Suspicious Execution Chain',
#     'protection_rx': 'Injection',
#     'puce_mutexes': 'Worm',
#     'putterpanda_mutexes': 'RAT',
#     'pwdump_file': 'Infostealer',
#     'qakbot': 'RAT',
#     'queries_programs': 'Exploit',
#     'ragebot': 'RAT',
#     'ramnit': 'RAT',
#     'ransomware_appends_extensions': 'Ransomware',
#     'ransomware_bcdedit': 'Ransomware',
#     'ransomware_dropped_files': 'Ransomware',
#     'ransomware_file_moves': 'Ransomware',
#     'ransomware_mass_file_delete': 'Ransomware',
#     'ransomware_message_ocr': 'Ransomware',
#     'ransomware_shadowcopy': 'Ransomware',
#     'ransomware_viruscoder': 'Ransomware',
#     'ransomware_wbadmin': 'Ransomware',
#     'rat_adzok': 'RAT',
#     'rat_beastdoor': 'RAT',
#     'rat_bifrose': 'RAT',
#     'rat_blackhole': 'RAT',
#     'rat_blackice': 'RAT',
#     'rat_blackshades': 'RAT',
#     'rat_bottilda': 'RAT',
#     'rat_buzus_mutexes': 'RAT',
#     'rat_comRAT': 'RAT',
#     'rat_darkshell': 'RAT',
#     'rat_delf': 'RAT',
#     'rat_dibik': 'RAT',
#     'rat_fexel_ip': 'RAT',
#     'rat_flystudio': 'RAT',
#     'rat_fynloski': 'RAT',
#     'rat_hikit': 'RAT',
#     'rat_hupigon': 'RAT',
#     'rat_jewdo': 'RAT',
#     'rat_koutodoor': 'RAT',
#     'rat_likseput': 'RAT',
#     'rat_madness': 'RAT',
#     'rat_mybot': 'RAT',
#     'rat_naid_ip': 'RAT',
#     'rat_netobserve': 'RAT',
#     'rat_pasta': 'RAT',
#     'rat_plugx': 'RAT',
#     'rat_rbot': 'RAT',
#     'rat_shadowbot': 'RAT',
#     'rat_siggenflystudio': 'RAT',
#     'rat_swrort': 'RAT',
#     'rat_travnet': 'RAT',
#     'rat_trogbot': 'RAT',
#     'rat_turkojan': 'RAT',
#     'rat_urxbot': 'RAT',
#     'rat_vertex': 'RAT',
#     'rat_xtreme': 'RAT',
#     'rat_zegost': 'RAT',
#     'rdp_mutexes': 'RAT',
#     'reads_user_agent': 'Stealth',
#     'renostrojan': 'Trojan',
#     'rovnix': 'Banker',
#     'rtf_unknown_character_set': 'Suspicious Office',
#     'rtf_unknown_version': 'Suspicious Office',
#     'runouce_mutexes': 'Worm',
#     'sadbot': 'RAT',
#     'self_delete_bat': 'Trojan',
#     'senna': 'RAT',
#     'sharpstealer_url': 'Infostealer',
#     'shellcode_writeprocessmemory': 'Injection',
#     'shiza': 'RAT',
#     'shutdown_system': 'Stealth',
#     'shylock': 'RAT',
#     'smtp_gmail': 'Web Mail',
#     'smtp_live': 'Web Mail',
#     'smtp_mail_ru': 'Web Mail',
#     'smtp_yahoo': 'Web Mail',
#     'snort_alert': 'C2',
#     'solarbot_url': 'BOT',
#     'spyrecorder': 'RAT',
#     'stackpivot_shellcode_createprocess': 'Rop',
#     'staser': 'RAT',
#     'stealth_hidden_icons': 'Stealth',
#     'stealth_hiddenfile': 'Stealth',
#     'stealth_system_procname': 'Stealth',
#     'stops_service': 'Anti-antivirus',
#     'suspicious_powershell': 'PowerShell',
#     'suspicious_process': 'Suspicious Execution Chain',
#     'suspicious_tld': 'C2',
#     'suspicious_write_exe': 'Downloader',
#     'sweetorange_mutexes': 'Exploit',
#     'sysinternals_tools_usage': 'Persistence',
#     'task_for_pid': 'Injection',
#     'terminates_remote_process': 'Persistence',
#     'tnega_mutexes': 'Trojan',
#     'trojan_bublik': 'RAT',
#     'trojan_ceatrg': 'Trojan',
#     'trojan_dapato': 'Trojan',
#     'trojan_emotet': 'Trojan',
#     'trojan_jorik': 'Trojan',
#     'trojan_kilim': 'Trojan',
#     'trojan_lethic': 'Trojan',
#     'trojan_lockscreen': 'Trojan',
#     'trojan_mrblack': 'Trojan',
#     'trojan_pincav': 'Trojan',
#     'trojan_redosru': 'Trojan',
#     'trojan_sysn': 'Trojan',
#     'trojan_vbinject': 'Trojan',
#     'trojan_yoddos': 'Trojan',
#     'tufik_mutexes': 'Virus',
#     'upatre': 'RAT',
#     'upatretd_mutexes': 'Trojan',
#     'urlshortcn_checkip': 'URLshort',
#     'urlspy': 'RAT',
#     'uroburos_file': 'RAT',
#     'uroburos_mutexes': 'RAT',
#     'vir_nebuler': 'Trojan',
#     'vir_pykse': 'Worm',
#     'virut': 'RAT',
#     'vnc_mutexes': 'RAT',
#     'wakbot': 'RAT',
#     'warbot_url': 'BOT',
#     'win32_process_create': 'WMI',
#     'winmgmts_process_create': 'WMI',
#     'winsxsbot': 'Worm',
#     'wmi_antivm': 'Anti-vm',
#     'wmi_persistance': 'Persistence',
#     'wmi_service': 'Persistence',
#     'worm_allaple': 'Worm',
#     'worm_kolabc': 'Worm',
#     'worm_palevo': 'Worm',
#     'worm_phorpiex': 'Worm',
#     'worm_psyokym': 'Worm',
#     'worm_renocide': 'Worm',
#     'worm_rungbu': 'Worm',
#     'worm_xworm': 'Worm'
# }

CAPE_SIGNATURE_CATEGORIES = {
    "Exploit": {
        "id": 1,
        "description": "Exploits an known software vulnerability or security flaw."
    },
    "PowerShell": {
        "id": 2,
        "description": "Leverages Powershell to attack Windows operating systems."
    },
    "Hacking tool": {
        "id": 3,
        "description": "Programs designed to crack or break computer and network security measures."
    },
    "Locker": {
        "id": 4,
        "description": "Prevents access to system data and files."
    },
    "Anti-analysis": {
        "id": 5,
        "description": "Constructed to conceal or obfuscate itself to prevent analysis."
    },
    "Suspicious PDF API": {
        "id": 6,
        "description": "Makes API calls not consistent with expected/standard behaviour."
    },
    "Suspicious Android API": {
        "id": 7,
        "description": "Makes API calls not consistent with expected/standard behaviour."
    },
    "Anti-antivirus": {
        "id": 8,
        "description": "Attempts to conceal itself from detection by anti-virus."
    },
    "Anti-vm": {
        "id": 9,
        "description": "Attempts to detect if it is being run in virtualized environment."
    },
    "Anti-Debug": {
        "id": 10,
        "description": "Attempts to detect if it is being debugged."
    },
    "Worm": {
        "id": 11,
        "description": "Attempts to replicate itself in order to spread to other systems."
    },
    "Cloud": {
        "id": 12,
        "description": "Makes connection to cloud service."
    },
    "Virus": {
        "id": 13,
        "description": "Malicious software program"
    },
    "Suspicious Office": {
        "id": 14,
        "description": "Makes API calls not consistent with expected/standard behaviour"
    },
    "Ransomware": {
        "id": 15,
        "description": "Designed to block access to a system until a sum of money is paid."
    },
    "Persistence": {
        "id": 16,
        "description": "Technique used to maintain presence in system(s) across interruptions that could cut off access."
    },
    "Injection": {
        "id": 17,
        "description": "Input is not properly validated and gets processed by an interpreter as part of a command or query."
    },
    "Dropper": {
        "id": 18,
        "description": "Trojan that drops additional malware on an affected system."
    },
    "Suspicious Execution Chain": {
        "id": 19,
        "description": "Command shell or script process was created by unexpected parent process."
    },
    "Trojan": {
        "id": 20,
        "description": "Presents itself as legitimate in attempt to infiltrate a system."
    },
    "RAT": {
        "id": 21,
        "description": "Designed to provide the capability of covert surveillance and/or unauthorized access to a target."
    },
    "C2": {
        "id": 22,
        "description": "Communicates with a server controlled by a malicious actor."
    },
    "Tor": {
        "id": 23,
        "description": "Intalls/Leverages Tor to enable anonymous communication."
    },
    "Web Mail": {
        "id": 24,
        "description": "Connects to smtp.[domain] for possible spamming or data exfiltration."
    },
    "Anti-sandbox": {
        "id": 25,
        "description": "Attempts to detect if it is in a sandbox."
    },
    "Stealth": {
        "id": 26,
        "description": "Leverages/modifies internal processes and settings to conceal itself."
    },
    "Packer": {
        "id": 27,
        "description": "Compresses, encrypts, and/or modifies a malicious file's format."
    },
    "Banker": {
        "id": 28,
        "description": "Designed to gain access to confidential information stored or processed through online banking."
    },
    "Point-of-sale": {
        "id": 29,
        "description": "Steals information related to financial transactions, including credit card information."
    },
    "Bypass": {
        "id": 30,
        "description": "Attempts to bypass operating systems security controls (firewall, amsi, applocker, etc.)"
    },
    "Crash": {
        "id": 31,
        "description": "Attempts to crash the system."
    },
    "IM": {
        "id": 32,
        "description": "Leverages instant-messaging."
    },
    "Rootkit": {
        "id": 33,
        "description": "Designed to provide continued privileged access to a system while actively hiding its presence."
    },
    "Adware": {
        "id": 34,
        "description": "Displays unwanted, unsolicited advertisements."
    },
    "Infostealer": {
        "id": 35,
        "description": "Collects and disseminates information such as login details, usernames, passwords, etc."
    },
    "WMI": {
        "id": 36,
        "description": "Leverages Windows Management Instrumentation (WMI) to gather information and/or execute a process."
    },
    "Downloader": {
        "id": 37,
        "description": "Trojan that downloads installs files."
    },
    "DynDNS": {
        "id": 38,
        "description": "Utilizes dynamic DNS."
    },
    "BOT": {
        "id": 39,
        "description": "Appears to be a bot or exhibits bot-like behaviour."
    },
    "Rop": {
        "id": 40,
        "description": "Exploits trusted programs to execute malicious code from memory to evade data execution prevention."
    },
    "Fraud": {
        "id": 41,
        "description": "Presents itself as a legitimate program and/or facilitates fraudulent activity."
    },
    "URLshort": {
        "id": 42,
        "description": "Leverages URL shortening to obfuscate malicious destination."
    },
    "Anti-emulation": {
        "id": 43,
        "description": "Detects the presence of an emulator."
    },
    "Cryptocurrency": {
        "id": 44,
        "description": "Facilitates mining of cryptocurrency."
    },
    "Bind": {
        "id": 45,
        "description": "Allows a resource to be sent or received across a network."
    },
    "Suspicious DLL": {
        "id": 46,
        "description": "Attempts to load DLL that is inconsistent with expected/standard behaviour."
    },
    "AntiVirus Hit": {
        "id": 1008,
        "description": "AntiVirus hit. File is infected."
    }
}

CAPE_DROPPED_SIGNATURES = [
    # 'origin_langid', 'apt_cloudatlas', 'apt_carbunak', 'apt_sandworm_ip',
    # 'apt_turlacarbon', 'apt_sandworm_url', 'apt_inception', 'rat_lolbot',
    # 'backdoor_vanbot', 'rat_sdbot', 'backdoor_tdss', 'backdoor_whimoo',
    # 'madness_url', 'volatility_svcscan_2', 'volatility_svcscan_3',
    # 'volatility_modscan_1', 'volatility_handles_1', 'volatility_devicetree_1',
    # 'volatility_ldrmodules_1', 'volatility_ldrmodules_2', 'volatility_malfind_2',
    # 'volatility_svcscan_1', 'detect_putty', 'powerworm', 'powershell_ddi_rc4',
    # 'powershell_di', 'powerfun', 'powershell_dfsp', 'powershell_c2dns',
    # 'powershell_unicorn', 'spreading_autoruninf', 'sniffer_winpcap',
    # 'mutex_winscp', 'sharing_rghost', 'exp_3322_dom', 'mirc_file', 'vir_napolar',
    # 'vertex_url', 'has_pdb', "process_martian", "rat_teamviewer", "antiav_detectfile",
    # "antiav_detectreg", "api_hammering", "raises_exception", "antivm_memory_available",
    # "recon_fingerprint", "application_raises_exception", "modifies_certificates",
    # "modifies_proxy_wpad", "stack_pivot_shellcode_apis", "infostealer_mail", "locates_browser",
    # "exploit_heapspray",
]


def get_category_id(sig: str) -> int:
    """
    This method returns the category ID for a given signature name
    :param sig: given signature name
    :return: the category ID
    """
    category = CAPE_SIGNATURES.get(sig, "unknown")
    metadata = CAPE_SIGNATURE_CATEGORIES.get(category, {})
    return metadata.get("id", 9999)


def get_signature_category(sig: str) -> str:
    """
    This method returns the category for a given signature name
    :param sig: given signature name
    :return: The category name
    """
    return CAPE_SIGNATURES.get(sig, "unknown")
