name: tests

variables:
  - group: unittest-samples

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: PipelineTemplates
      type: github
      name: CybercentreCanada/assemblyline-pipeline-templates
      ref: refs/heads/main
      endpoint: github-repo-sa
      trigger: none
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: none

extends:
  template: stages/test-service.yaml@PipelineTemplates
  parameters:
    samples_repo: unittest-samples
    test_container: "false"
    python_versions:
      - "3.11"
      - "3.12"
    